### ISSUE TITLE
 Build Workflow Runs All Jobs Twice

### ISSUE THREAD

**Issue by Matthew-Grayson** [cisagov/skeleton-generic#174]
# 🐛 Summary #

Creating a PR initiates two instances of each build job. 'Run diagnostics' and 'lint' both run twice. These are spawned by .github/workflows/build.yml.

![image](https://github.com/cisagov/skeleton-generic/assets/106278637/cb6d10d4-6f89-42a4-85f6-7db3e624bf8b)

**Comment by jsf9k** [comment]
This is intentional:
- We need workflows to run on a `push` event so that testing happens on branches even before a PR is created.
- We need workflows to run on a `pull_request` event.  This is so that testing happens on branches created from forks of our repos when the forker creates a PR back to our repo to integrate his or her changes.
